# LOGIN
### login
POST http://localhost:8080/login
Content-Type: application/json

# {
#     "cpf":"22061446035",
#     "secret":"can't-tell-you"
# }

{
    "cpf":"488.569.610-08",
    "secret":"really-good-one"
}

# ACCOUNTS
### get all accounts
GET http://localhost:8080/accounts

### create new account
POST http://localhost:8080/accounts
Content-type: application/json

# {
#     "name": "first client",
#     "cpf": "22061446035",
#     "secret": "can't-tell-you"
# }

# {
#     "name": "second client",
#     "cpf": "045.591.180-00",
#     "secret": "still-can't-tell-you"
# }

{
    "name": "another client",
    "cpf": "488.569.610-08",
    "secret": "really-good-one"
}

### get account balance
GET http://localhost:8080/accounts/d9e8bde1-a36e-48cd-b90f-08adeef3460a/balance

# TRANSFERS
### get all transfers
GET http://localhost:8080/transfers

### create transfer
POST http://localhost:8080/transfers
Content-type: application/json
Authorization: Bearer <JWT>

{
    "account_destination_id": "438e4746-fb04-4339-bd09-6cba20561835",
    "amount": 500
}
