# testing a custom workflow

name: Suricate Bank CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        run: make metalint

