name: Suricate Bank CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/*'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - uses: actions/cache@v3
          with:
            path: ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: |
              ${{ runner.os }}-go-
    
        - name: test
          run: go test -v ./...

        - name: build
          run: go build -v ./...

  build-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
